spring:
  application:
    name: JustDoIt
  data:
    mongodb:
      uri: mongodb://localhost:27017/justdoit
      database: justdoit
server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true

